#!/bin/bash

sudo yum install -y jq
sudo yum install -y curl

sudo yum install -y python3
sudo yum install -y python3-pip
sudo pip3 install flask

aws s3 cp s3://wsi-1234-iost-artifactory/app.py ./

sudo mkdir  /var/log/app
sudo chmod 777 /var/log/app
sudo touch /var/log/app/app.log
sudo chmod 777 /var/log/app/app.log
sudo yum install -y amazon-cloudwatch-agent

echo '{
    "logs": {
        "logs_collected": {
            "files": {
                "collect_list": [
                    {
                        "file_path": "/var/log/app/app.log",
                        "log_group_name": "/aws/ec2/wsi",
                        "log_stream_name": "api_{instance_id}",
                        "timezone": "UTC"
                    }
                ]
            }
        }
    }
}' | sudo tee /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json > /dev/null

nohup python3 app.py &

sudo systemctl start amazon-cloudwatch-agent
sudo systemctl enable amazon-cloudwatch-agent








// 다른 명령어들
  scp -i ~/Desktop/key-peir/key-i-make-bastion.pem ~/Desktop/key-peir/asdwqsd-auto.pem ec2-user@43.202.64.109:./
